# Generated by Django 2.1.5 on 2019-02-07 16:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='script',
        ),
        migrations.AddField(
            model_name='deploy',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='container',
            name='deploy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Deploy'),
        ),
    ]
