# Generated by Django 2.1.5 on 2019-02-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190207_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=256, null=True)),
                ('image_tag', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_port', models.IntegerField(blank=True, null=True)),
                ('out_port', models.IntegerField(blank=True, null=True)),
                ('path_inside', models.CharField(blank=True, max_length=256, null=True)),
                ('path_outside', models.CharField(blank=True, max_length=256, null=True)),
                ('mode', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='container',
            name='deploy',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='image_tag',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='params',
        ),
        migrations.AddField(
            model_name='deploy',
            name='params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Params'),
        ),
        migrations.AddField(
            model_name='image',
            name='deploy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Deploy'),
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
    ]
