# Generated by Django 2.1.5 on 2019-02-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190207_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='deploy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Deploy'),
        ),
    ]
