# Generated by Django 2.1.5 on 2019-02-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190207_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Image'),
        ),
    ]
